baseURL = "https://mholtzscher.github.io/"
languageCode = "en-us"
title = "Michael Holtzscher"
theme="ghostwriter"
copyright = "Michael Holtzscher"
googleAnalytics = "UA-75497945-1"


[Author]
    name = "Michael Holtzscher"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Learning Everyday"
    github = "https://github.com/mholtzscher"
    linkedin = "https://www.linkedin.com/in/michael-holtzscher-813a79117/"
    twitter = "https://twitter.com/mholtzscher"
    email = "mholtz@protonmail.com"
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

